### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by fallenoak** [wowserhq/wowser#108]
Now that several language constructs used by Wowser are becoming widely supported in current versions of mainstream browsers, it's probably time to upgrade to Babel 6 to take advantage of modular language fallbacks.

In particular, I believe the fallback for ```for...of``` can be removed immediately, and once Firefox 45 and Chrome 49 ship, ```class``` should be a first class citizen in Firefox, Chrome, and Edge.

**Comment by timkurvers** [comment]
:+1: Let's tackle this after the move to wowserhq in #107.

**Comment by fallenoak** [comment]
Browsers are getting dangerously close to 100% ES6 compatibility. Maybe we can tackle this one soon.

**Comment by timkurvers** [comment]
I suppose one of the few features we'd still need Babel for would be import/export?

**Comment by fallenoak** [comment]
I think that's right. And possibly: ```Array.includes()```, ```Object.values```, ```Object.entries```, and the ```::``` bind operator.

**Comment by fallenoak** [comment]
Closed by #157
