### ISSUE TITLE
Font rendering in Firefox on OSX

### ISSUE THREAD

**Issue by timkurvers** [wowserhq/wowser#121]
As outlined [here](https://maximilianhoffmann.com/posts/better-font-rendering-on-osx) light-on-dark font rendering on OSX is a tricky beast. We're already using `-webkit-font-smoothing: antialiased` for WebKit browsers.

We should consider using `-moz-osx-font-smoothing: grayscale` for Firefox, too.

**Before**

![screen shot 2016-02-18 at 11 40 13](https://cloud.githubusercontent.com/assets/378235/13140893/f0a3e3ae-d634-11e5-9669-7004f9e316dd.png)

**After**

![screen shot 2016-02-18 at 11 40 01](https://cloud.githubusercontent.com/assets/378235/13140907/00611596-d635-11e5-9575-e205176ddc72.png)

**Comment by fallenoak** [comment]
Hrm, can't say I've noticed this on FF OS X myself. Is there a trick to cause it?

**Comment by timkurvers** [comment]
Wait, it doesn't happen for you? :open_mouth:

**Comment by fallenoak** [comment]
Here's what I see on current HEAD:
<img width="1552" alt="screen shot 2016-02-18 at 10 19 47 am" src="https://cloud.githubusercontent.com/assets/13418124/13149993/51e74216-d629-11e5-9a2d-0ad07c924eda.png">

**Comment by timkurvers** [comment]
Ah, interesting! :+1: Will test on a Retina display a bit later today.

**Comment by timkurvers** [comment]
Covered by #122.
