### ISSUE TITLE
Upgrade to three.js r77

### ISSUE THREAD

**Issue by fallenoak** [wowserhq/wowser#133]
Currently, Wowser uses r73. Several new versions have been released since r73, and the animation system has been overhauled yet again.

Before we fall too far behind, we should upgrade. r77 is the current version of three.

**Comment by timkurvers** [comment]
Indeed, sounds like a good plan! 👍

**Comment by fallenoak** [comment]
Upgrading to the latest version of three should also resolve those pesky texture unit errors that have been appearing in the console for the last few months.

**Comment by timkurvers** [comment]
This can probably be closed now, right?

**Comment by fallenoak** [comment]
Closed by #145
