### ISSUE TITLE
Possible double trademark infringement

### ISSUE THREAD

**Issue by stas730** [wowserhq/wowser#172]
First (IIRC): When I played WoW 0.5.3 alpha, I saw something like "wowser" when using some button.
Second: "WoW" is a trademark, of course.

**Comment by fallenoak** [comment]
As far as I know, Blizzard does not have a trademark on the word _wow_ -- they do maintain trademarks on _World of Warcraft_ and just plain _Warcraft_ (among other things), but this project is named _Wowser_, not _Warcraftser_. See Blizzard's [trademark page](http://us.blizzard.com/en-us/company/legal/trademarks.html) for a full accounting of game-related trademarks Blizzard maintains.

Additionally, the presence of a word in a product does not immediately establish the word as a trademark. For instance, the word _quest_ appears dozens of times in the game's UI, but _quest_ is not a trademark related to Blizzard or World of Warcraft.

Finally, _wowser_ exists as a plain English word. To quote trusty old [Merriam-Webster](https://www.merriam-webster.com/dictionary/wowser):

> Wowser is a delightful word with an interesting background, though its ultimate origin is unknown. The word first appeared in print in 1899, in the Australian journal Truth, and was instantly popular in Australia. It spread to New Zealand, where it remains in use, and then eventually arrived in England, possibly brought by the Australian troops who served there during World War I. The American writer and editor H. L. Mencken liked "wowser" and attempted to introduce it in the United States. He used the word frequently in American Mercury, the literary magazine he edited. Despite Mencken's efforts the term never truly caught on in American English, though it is used occasionally.
