### ISSUE TITLE
Implement some Battle.net stuff

### ISSUE THREAD

**Issue by stas730** [wowserhq/wowser#173]
Some Battle.net stuff is not implemented both in clients and servers. It's Battle.net for other games. We're playing WoW, but it's also designed for Diablo III and StarCraft II. You can see some achievements and items, for example.
Not implemented stuff:
1. Battle.net friends from other games
1. 1. Battle.net friend login info window [non-Blizzard addon for vanilla: http://addons.us.to/addon/friendsframe]
2. RealID
3. Battle.net Authenticator
Warning: Do not ask TrinityCore. They're decided to not implement this.

**Comment by Warpten** [comment]
Because it's almost impossible for 3.3.5, ultra hard for 4.3.4 and too annoying for 6.x/7.x

**Comment by stas730** [comment]
Why?

**Comment by Deamon87** [comment]
Because reasons :) In 3.3.5 they used modules for BN2, which were encrypted and RSA signed. And client checks this RSA sign. So to implement BN2 features you would have to go through a lot of struggle, patching client(cause it's nearly impossible to crack RSA), reverse the BN2 protocol or create a custom module and all other shit.

Too much of struggle to gain very little. So noone bothers to do such unrewarding work.

**Comment by stas730** [comment]
I hate DRM.

**Comment by Warpten** [comment]
Streamed modules by the server. It's only in cataclysm that they (by mistake) shipped modules with actual symbols, and not obfuscated.

**Comment by stas730** [comment]
If a part of project is impossible, stop developing the whole project.

**Comment by majorcyto** [comment]
Yeah, don't think that is up to you.. and that is really pretty rude of you to say lol.

**Comment by fallenoak** [comment]
Thanks for the request!

As others have pointed out, Battle.net support for 335a is a bit of a pipe dream. If, somehow, it becomes possible to implement down the road, we'd certainly consider it. For now, we're more than busy just working out how things work, and tackling implementations of "simple" things like rendering, networking, UI, etc.

Closing this issue, as I don't think there's much more to add.

**Comment by stas730** [comment]
Downgrade requested: https://github.com/wowserhq/wowser/issues/175
