### ISSUE TITLE
Downgrade if Battle.net cannot be implemented

### ISSUE THREAD

**Issue by stas730** [wowserhq/wowser#175]
If Battle.net stuff cannot be implemented, WoW version must be downgraded to avoid unimplementable Battle.net stuff. 3.3.5.12340 is not good.
If older WotLK patches can't be used, then use TBC.
If it's not possible and full client will be never implemented then Wowser must be abandoned.

**Comment by fallenoak** [comment]
@stas730 There's no reason to downgrade Wowser to a pre-WotLK era of the game. 12340 is just fine to work with, and we'll continue to do so.

**Comment by stas730** [comment]
Why if you cannot even fully implement it?
