### ISSUE TITLE
Godot Game Engine

### ISSUE THREAD

**Issue by infosisio** [wowserhq/wowser#181]
Have you thought of using it ? You should at least take a look. 
Very decent technology there and scripting that is truly approachable to everyone.

Imagining this kind of project as modules that everyone can assemble in powerful new ways to put their own spin on what we know as WoW, and in full source code freedom, is just mind blowing.

**Comment by fallenoak** [comment]
Hey there!

The goal of Wowser is to write a clean, browser-compatible implementation of a client that looks and feels like the original 3.3.5a client, running on the versions of assets that shipped in that patch.

As a result, using an existing game or rendering engine isn't a good choice.

We originally tried using threejs in Wowser, but there were just too many cases where threejs's (very valid) opinions on how rendering should work didn't jive with how the game itself works.

Our current approach is to carefully determine how the original game works, and implement a similar approach in Wowser (from scratch).

You could consider Wowser more in line with what ScummVM has done for old Sierra and LucasArts adventure games, just tackling a more recent game and targeting the browser as our runtime environment.

**Comment by infosisio** [comment]
@fallenoak The thing is, if you do it in Godot you are covering all platforms, web included :)

**Comment by fallenoak** [comment]
@infosisio Per my earlier comments, Wowser isn't an attempt to create a new game; rather, Wowser is an attempt to reimplement the 3.3.5a client from scratch.

Engines like Godot (and rendering engines like Ogre and threejs) are great for someone creating a new game. For a project like Wowser, however, too many decisions are made by these off-the-shelf engines--decision that get in the way of an accurate reimplementation.
