### ISSUE TITLE
Placement of certain M2s seems off

### ISSUE THREAD

**Issue by timkurvers** [wowserhq/wowser#95]
Waterfalls from Stonewrought Dam (`-4660.336900981519, -3325.714373498674, 296`)

![screen shot 2016-01-09 at 21 50 53](https://cloud.githubusercontent.com/assets/378235/12218298/494da3f2-b71b-11e5-8b91-232e0b1f9f2f.png)

Bridge leading to Stonewatch Keep (`-9542.955576414317, -2918.528868503445, 129.48000000000025`)

![screen shot 2016-01-09 at 21 56 11](https://cloud.githubusercontent.com/assets/378235/12218309/ed0742a0-b71b-11e5-88ff-24f73fad9634.png)

**Comment by timkurvers** [comment]
Fixed by #104, thanks @fallenoak! :smile:

**Comment by fallenoak** [comment]
Never again do I want to spend 4 hours trial and error'ing may way through placement issues. But I bet it happens at least a dozen more times, as we begin to implement more content. :smile:
